import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { FileUp, LogOut, Save, UserPlus } from 'lucide-react'
import { Brand } from '../components/Brand'
import { addTeamMember, getTeamProject, signIn, signOut, updateTeamProject, uploadPitchDeck, type Project } from '../services/dashboards'
import { isSupabaseConfigured, supabase } from '../services/supabase'

const EMPTY: Project = { id: '', project_name: '', category: '', description: '', problem_statement: '', solution: '', github_url: '', demo_url: '', pitch_deck_url: '' }

export function Team() {
  const [authenticated, setAuthenticated] = useState(false)
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('')
  const [project, setProject] = useState<Project>(EMPTY)
  const [memberEmail, setMemberEmail] = useState(''); const [file, setFile] = useState<File | null>(null)
  const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)

  const load = async () => { setLoading(true); setError(''); try { setProject(await getTeamProject()) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load your project.') } finally { setLoading(false) } }
  useEffect(() => { if (!supabase) return; supabase.auth.getSession().then(({ data }) => setAuthenticated(Boolean(data.session))); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => setAuthenticated(Boolean(session))); return () => listener.subscription.unsubscribe() }, [])
  useEffect(() => { if (authenticated) void load() }, [authenticated])
  const login = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { await signIn(email, password) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to sign in.') } finally { setLoading(false) } }
  const save = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { await updateTeamProject(project.id, project); if (file) { const pitchDeck = await uploadPitchDeck(project.id, file); setProject((current) => ({ ...current, pitch_deck_url: pitchDeck })) }; setMessage('Project saved successfully.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save your project.') } finally { setLoading(false) } }
  const addMember = async () => { if (!memberEmail.trim()) return; setLoading(true); setError(''); try { await addTeamMember(project.id, memberEmail); setMemberEmail(''); setMessage('Team member added.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to add team member.') } finally { setLoading(false) } }

  if (!isSupabaseConfigured) return <Notice />
  if (!authenticated) return <div className="admin-login"><form onSubmit={login} className="admin-login-card"><Brand /><div className="section-label">/ TEAM ACCESS</div><h1>Your<br /><span>venture.</span></h1><p>Sign in using the email you registered with.</p><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email" required /><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Password" required />{error && <span className="field-error">{error}</span>}<button className="primary" disabled={loading}>Unlock <span>↗</span></button></form></div>

  return <div className="admin-page"><header className="admin-nav"><Brand /><span className="form-count">TEAM / VENTURE ROOM</span><button className="admin-btn" onClick={() => void signOut()}><LogOut size={15} /> Logout</button></header><div className="admin-body"><div className="admin-head"><div><div className="section-label">/ YOUR VENTURE</div><h1>Build your <span>pitch.</span></h1></div></div>{error && <p className="admin-alert">{error}</p>}{message && <p className="team-success">{message}</p>}<div className="team-layout"><form className="team-project-form" onSubmit={save}><label>Project name<input value={project.project_name} onChange={(event) => setProject({ ...project, project_name: event.target.value })} /></label><label>Track<input value={project.category || ''} onChange={(event) => setProject({ ...project, category: event.target.value })} /></label><label>Project description<textarea value={project.description || ''} onChange={(event) => setProject({ ...project, description: event.target.value })} /></label><label>Problem statement<textarea value={project.problem_statement || ''} onChange={(event) => setProject({ ...project, problem_statement: event.target.value })} /></label><label>Solution<textarea value={project.solution || ''} onChange={(event) => setProject({ ...project, solution: event.target.value })} /></label><label>GitHub URL<input type="url" value={project.github_url || ''} onChange={(event) => setProject({ ...project, github_url: event.target.value })} placeholder="https://github.com/..." /></label><label>Demo URL<input type="url" value={project.demo_url || ''} onChange={(event) => setProject({ ...project, demo_url: event.target.value })} placeholder="https://..." /></label><label>Pitch deck PDF<input type="file" accept="application/pdf" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label>{project.pitch_deck_url && <p className="admin-note">Pitch deck uploaded.</p>}<button className="primary" disabled={loading}><Save size={15} /> {loading ? 'Saving...' : 'Save project'}</button></form><aside className="team-member-card"><h2>Team members</h2><p>Add a participant who has already registered with Hack Tank.</p><input type="email" value={memberEmail} onChange={(event) => setMemberEmail(event.target.value)} placeholder="Participant email" /><button className="admin-btn primary-btn" onClick={() => void addMember()} disabled={loading}><UserPlus size={15} /> Add member</button><div className="team-upload"><FileUp size={22} /><p>Your pitch deck can be uploaded as a PDF (10 MB max).</p></div></aside></div></div></div>
}

function Notice() { return <div className="admin-login"><div className="admin-login-card"><Brand /><h1>Supabase setup required</h1><p>Configure Supabase before opening the team dashboard.</p><Link className="primary" to="/">Back home</Link></div></div> }
